image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

services:
    - docker:19.03.12-dind
build:
    image: docker:19.03.12
    stage: build
    before_script:
        - apk add --no-cache docker-compose
        - docker info
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker-compose build
        - docker tag kldemo-customers-web:latest $CI_REGISTRY/kldemo-customers-web:$CI_COMMIT_SHA
        - docker tag kldemo-customers-web:latest $CI_REGISTRY/kldemo-customers-web:latest
        - docker push $CI_REGISTRY/kldemo-customers-web:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY/kldemo-customers-web:latest