image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375

services:
    - docker:19.03.12-dind
build:
    image: docker:19.03.12
    stage: build
    before_script:
        - apk add --no-cache docker-compose
        - docker info
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker-compose build
        - docker push $CI_REGISTRY/alexander/kubernetesloadbalancing/kldemo-customers-web:latest