image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build

build:
    image: docker:19.03.12
    stage: build
    services:
        - docker:19.03.12-dind
        - docker info
    before_script:
        - apk add --no-cache docker-compose
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker-compose build
        - docker push $CI_REGISTRY/alexander/kubernetesloadbalancing/kldemo-customers-web:latest