image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build
    - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
    
services:
    - docker:18.09.7-dind
build:
    stage: build
    image: docker:stable
    before_script:
        - apk add --no-cache docker-compose
        - docker info
    script:
        - echo "Building docker images"
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker-compose build
        - docker tag kldemo-customers-web:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker tag kldemo-customers-web:latest $CI_REGISTRY_IMAGE:latest
        - echo "Pushing docker images to registry"
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:latest
deploy:
    stage: deploy
    image: bitnami/kubectl:latest
    variables:
      CI_DEBUG_TRACE: "true"
    environment:
        name: staging
    script:
        - kubectl delete secret docker-registry registry-credentials --ignore-not-found
        - echo $CI_REGISTRY
        - echo $CI_DEPLOY_USER
        - echo $CI_DEPLOY_PASSWORD
        - kubectl create secret docker-registry registry-credentials --docker-server=$CI_REGISTRY --docker-username=gitlab+deploy-token-3 --docker-password=XsynJR4RKyReyb9-sVfd --docker-email=$GITLAB_USER_EMAIL
        - echo "Deploy to staging environment. You must supply credentials already!"
        - kubectl apply -f kl-demo-deployment.yaml -f kl-demo-service.yaml -f kl-demo-ingress.yaml

