stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
    - docker:20.10.16-dind
build:
  stage: build
  tags:
    - docker
  image: docker:stable
  before_script:
    - apk add --no-cache docker-compose
    - docker info
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker tag kldemo-customers-web:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag kldemo-customers-web:latest $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
deploy:
  stage: deploy
  tags:
    - docker
  image: 
     name: bitnami/kubectl:latest
     entrypoint: [""]
  environment:
        name: staging
  script:
    - kubectl config get-contexts
    - kubectl config use-context ezlab/kubernetes-agent:leo
    - kubectl apply -f deploy/kl-demo-service-namespace.yaml
    - kubectl delete secret docker-registry registry-credentials --ignore-not-found --namespace=ezlab-load-balancing-demo
    - kubectl create secret docker-registry registry-credentials --docker-server=$CI_REGISTRY --docker-username=$EZLAB_DEPLOY_USER --docker-password=$EZLAB_DEPLOY_PWD --namespace=ezlab-load-balancing-demo
    - kubectl apply -f deploy
    - kubectl rollout restart deployment kldemo-customers-web-deployment --namespace=ezlab-load-balancing-demo
    - kubectl rollout restart deployment kldemo-nginx-deployment --namespace=ezlab-load-balancing-demo