version: '3.4'

services:
  kldemo-customers-web:
    image: kldemo-customers-web
    build:
      context: .
      network: host
      dockerfile: web/Weather.Web/Dockerfile
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      - main-network
    expose:
      - "8080"
  kldemo-nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '8066:80'
    depends_on:
      - kldemo-customers-web
    restart: always
    networks:
      - main-network

networks:
  main-network:
    driver: bridge