apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kldemo-nginx-ingress
  labels:
    app: kldemo
spec:
  rules:
    - http:
        paths:
          - path: /kl-demo
            backend:
              serviceName: kldemo-nginx
              servicePort: 8081