apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kldemo-nginx-ingress
  labels:
    app: kldemo
spec:
  defaultBackend:
    service:
      name: kldemo-nginx
      port:
        number: 8081