apiVersion: v1
kind: Service
metadata:
  name: kldemo-nginx
  labels:
    app: kdemo
spec:
  type: NodePort
  ports:
    - port: 8666
  selector:
    app: kldemo-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: kldemo-customers-web
  labels:
    app: kdemo
spec:
  type: ClusterIP
  selector:
    app: kldemo-customers-web
  ports:
    - port: 8080
