apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kldemo-nginx-ingress
  labels:
    app: kldemo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /kl-demo
            pathType: Prefix
            backend:
              service:
                name: kldemo-nginx
                port:
                  number: 8081